'use client'

// import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

import localFont from "next/font/local";
import { useRef } from "react";
import Link from "next/link";
import Image from "next/image";

const myFont = localFont({
  src: "./font/Exo2-VariableFont_wght.ttf" ,
  display: "swap",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const menu=useRef()
  const ul=useRef()
  const aco=useRef()
  const footer=useRef()
  function list(){
    menu.current.style.display='flex'
    setTimeout(()=>{
      ul.current.children[0].style.transform='translateX(10%)'
      ul.current.children[2].style.transform='translateX(0%)'
    },300)
    setTimeout(()=>{
      ul.current.children[1].style.transform='translateX(0%)'
      ul.current.children[3].style.transform='translateX(15%)'
    },400)
    setTimeout(()=>{
      ul.current.children[4].style.transform='translateX(0%)'
    },500)
  }
  function close(){
    menu.current.style.display='none'
    ul.current.children[0].style.transform='translateX(-100%)'
    ul.current.children[1].style.transform='translateX(-100%)'
    ul.current.children[2].style.transform='translateX(100%)'
    ul.current.children[3].style.transform='translateX(100%)'
    ul.current.children[4].style.transform='translateX(-100%)'

  }

  function open(){
    aco.current.style.display='flex'
    footer.current.style.display='none'
  }
  function close2(){
    aco.current.style.display='none'
    footer.current.style.display='flex'
  }

  const load=useRef()
  setTimeout(()=>{
    load.current.style.display='none'
  },4000)

  return (
    <html lang="en" className="bg-black">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
      </head>
      <body className={myFont.className}>

     <div ref={load} className="w-[100%] h-[100vh] fixed top-0 z-50 bg-black flex justify-center items-center">
          <Image
            src="/14.gif"
            alt="Picture of the author"
            width="3000000000"
            height="400000000"
            style={{
              width: "300px",
              height: "70px",
              objectFit: "cover",
            }}
              ></Image>
     </div>

        <header className="w-[100%] h-[10vh] fixed top-0 z-50 text-white flex">
          <div className="w-[55%] h-[100%] flex justify-end items-center">
            <h2 className="text-[1.8rem] font-bold uppercase">bugatti</h2>
          </div>
          <div className="w-[45%] h-[100%] flex justify-center items-center">
          <i onClick={list} className="bi bi-list text-[1.8rem] font-bold cursor-pointer"></i>
          </div>
        </header>
        <div ref={menu} style={{display:'none',}} className="w-[100%] h-[100%] flex flex-wrap fixed bg-black top-0 z-50">
        <div className="w-[100%] h-[10vh] text-white flex">
          <div className="w-[55%] h-[100%] flex justify-end items-center">
            <h2 className="text-[1.8rem] font-bold uppercase">bugatti</h2>
          </div>
          <div className="w-[45%] h-[100%] flex justify-center items-center">
          <i onClick={close} className="bi bi-x-circle text-[1.8rem] font-bold cursor-pointer"></i>
          </div>
        </div>
        <ul ref={ul} className="w-[100%] h-[80vh] overflow-hidden flex flex-wrap">
          <li style={{transform:'translateX(-100%)'}} className="w-[100%] h-[20%] hover:text-blue-700 transition-all duration-300 flex justify-center items-center text-[2rem] lg:text-[4rem] xl:text-[6rem] text-white uppercase">
            <Link href=''>
              <span className="text-[.7rem] lg:[1rem] xl:text-[1.5rem] inline-block translate-y-[-135%]">01</span>
            BUGATTI LIFESTYLE            
            </Link>
          </li>
          <li style={{transform:'translateX(-100%)'}} className="w-[100%] h-[20%] hover:text-blue-700 transition-all duration-300 flex justify-center items-center text-[2rem] lg:text-[4rem] xl:text-[6rem] text-white uppercase">
            <Link href=''>
            <span className="text-[.7rem] lg:[1rem] xl:text-[1.5rem] inline-block translate-y-[-135%]">02</span>
            BUGATTI HERITAGE            
            </Link>
          </li>
          <li style={{transform:'translateX(100%)'}} className="w-[100%] h-[20%] hover:text-blue-700 transition-all duration-300 flex justify-center items-center text-[2rem] lg:text-[4rem] xl:text-[6rem] text-white uppercase">
            <Link href=''>
            <span className="text-[.7rem] lg:[1rem] xl:text-[1.5rem] inline-block translate-y-[-135%]">03</span>
            MODELS
            </Link>
          </li>
          <li style={{transform:'translateX(100%)'}} className="w-[100%] h-[20%] hover:text-blue-700 transition-all duration-300 flex justify-center items-center text-[2rem] lg:text-[4rem] xl:text-[6rem] text-white uppercase">
            <Link href=''>
            <span className="text-[.7rem] lg:[1rem] xl:text-[1.5rem] inline-block translate-y-[-135%]">04</span>
            CUSTOMIZATION
            </Link>
          </li>
          <li style={{transform:'translateX(-100%)'}} className="w-[100%] h-[20%] hover:text-blue-700 transition-all duration-300 flex justify-center items-center text-[2rem] lg:text-[4rem] xl:text-[6rem] text-white uppercase">
            <Link href=''>
            <span className="text-[.7rem] lg:[1rem] xl:text-[1.5rem] inline-block translate-y-[-135%]">05</span>
            OWNERSHIP
            </Link>
          </li>
        </ul>
        <div className="w-[100%] h-[10vh]">
          <ul className="w-[100%] h-[100%] flex justify-center gap-5 items-center text-white text-[.8rem]">
            <li className="hover:text-blue-700 transition-all duration-300">
              <Link href=''>
              About Us
              </Link>
            </li>
            <li className="hover:text-blue-700 transition-all duration-300">
              <Link href=''>
              Contact
              </Link>
            </li>
            <li className="hover:text-blue-700 transition-all duration-300">
              <Link href=''>
              Find a Dealer
              </Link>
            </li>
            <li className="hover:text-blue-700 transition-all duration-300">
              <Link href=''>
              News & Zeitgeist
              </Link>
            </li>   
          </ul>
        </div>
        
        </div>

        {children}

        <footer ref={footer} className="w-[100%] h-[13vh] fixed top-[87%] z-40 flex flex-wrap justify-center content-between text-white">
          <div className="w-[100%] lg:w-[75%] h-[50%] bg-[rgba(49,49,49,0.5)] flex">
            <div className="w-[33%] lg:w-[15%] h-[100%] flex justify-center items-center uppercase text-[.7rem] lg:text-[.8rem]">english</div>
            <div className="w-[33%] lg:w-[70%] h-[100%] flex justify-center items-center">
            <Image
            src="/13.png"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "29px",
              height: "20px",
              objectFit: "cover",
            }}
          ></Image>
            </div>
            <div className="w-[33%] lg:w-[15%] h-[100%] flex justify-center items-center uppercase text-[.7rem] lg:text-[.8rem] text-nowrap cursor-pointer">audio off</div>
          </div>
          <div className="w-[100%] lg:w-[75%] h-[40%] flex bg-[rgba(49,49,49,0.5)]">
            <ul className="w-[65%] h-[100%] flex justify-end gap-5 items-center uppercase text-[.5rem] lg:text-[.8rem]">
              <li className="flex gap-2 items-center">
              <Image
            src="/16.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
          ></Image>
          21.47 - 25.19  1/100 km
              </li>
              <li className="flex gap-2 items-center">
              <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
          ></Image>
          486.72 - 571.63  g/km
              </li>
            </ul>
            <div className="w-[35%] h-[100%] flex justify-end px-10 items-center uppercase text-[1.2rem]">
            <i onClick={open} className="bi bi-chevron-down text-white cursor-pointer"></i>
            </div>
          </div>
        </footer>

        <div ref={aco} style={{display:'none'}} className="w-[100%] h-[60vh] overflow-hidden z-40 fixed top-[50%] flex justify-center">
          <div className="w-[100%] lg:w-[75%] h-[60vh] overflow-y-scroll bg-[rgba(49,49,49,0.5)] s">
            <div className="w-[100%] h-[1200px] xl:h-[150vh] text-[1rem] text-zinc-300 flex flex-wrap content-start">
              <div className="w-[100%] h-[50px] xl:h-[10%] flex items-center justify-end px-10">
             <i onClick={close2} className="bi bi-chevron-up text-white cursor-pointer"></i>
              </div>
              <ul className="w-[100%] xl:w-[49%] h-[200px] xl:h-[28%] p-5 flex flex-wrap gap-2 justify-center">
                <li className="w-[100%] text-[1.5rem] mb-5">Chiron/Chiron Sport (WLTP)</li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
              ></Image>
                  Fuel Consumption (combined): 25.19 1/100 km
              </li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
                ></Image>
                CO2 emissions (combined) 571.63 g/km
                </li>
              </ul>
              <ul className="w-[100%] xl:w-[49%] h-[200px] xl:h-[28%] p-5 flex flex-wrap gap-2 justify-center">
                <li className="w-[100%] text-[1.5rem] mb-5">W16 Mistral</li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
              ></Image>
                  Fuel Consumption (combined): Not applicable
              </li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
                ></Image>
                CO2 emissions (combined) Not applicable
                </li>
              </ul>
              <ul className="w-[100%] xl:w-[49%] h-[200px] xl:h-[28%] p-5 flex flex-wrap gap-2 justify-center">
                <li className="w-[100%] text-[1.5rem] mb-5">Chiron Super Sport</li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
              ></Image>
                  Fuel Consumption (combined): 21.47 1/100 km
              </li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
                ></Image>
                CO2 emissions (combined) 486.72  g/km
                </li>
              </ul>
              <ul className="w-[100%] xl:w-[49%] h-[200px] xl:h-[28%] p-5 flex flex-wrap gap-2 justify-center">
                <li className="w-[100%] text-[1.5rem] mb-5">Centodieci</li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
              ></Image>
                  Fuel Consumption (combined): 21.47 1/100 km
              </li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
                ></Image>
                CO2 emissions (combined) NA
                </li>
              </ul>
              <ul className="w-[100%] xl:w-[49%] h-[200px] xl:h-[28%] p-5 flex flex-wrap gap-2 justify-center">
                <li className="w-[100%] text-[1.5rem] mb-5">Bolide</li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
              ></Image>
                  Fuel Consumption (combined): Not applicable
              </li>
                <li className="w-[100%] flex text-[.9rem] gap-2">
                <Image
            src="/17.svg"
            alt="Picture of the author"
            width="300000"
            height="400000"
            style={{
              width: "25px",
              height: "25px",
              objectFit: "cover",
            }}
                ></Image>
                CO2 emissions (combined) Not applicable
                </li>
              </ul>
            </div>
          </div>
        </div>
        </body>
    </html>
  );
}
